project:
  type: website
  output-dir: docs

website:
  title: "Davis Backyard Museum BioBlitz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

